### ISSUE TITLE
Incorrect validation of API keys

### ISSUE THREAD

**Issue by andrewhancox** [moodlehq/filter_fulltranslate#4]
See PR3...

**Comment by berthelemy** [comment]
I think I have the same problem. I have a 39 character API key, which contains a hyphen and an underscore. So, at the moment, I'm unable to use the plugin.

**Comment by andrewhancox** [comment]
Mark, I've just updated my PR with some feedback from @mudrd8mz - in the mean-time you can grab the working version from:
https://github.com/andrewhancox/filter_fulltranslate

**Comment by mudrd8mz** [comment]
Thanks both. I just released a new version 2021031000 with Andrew's fix.
