### ISSUE TITLE
Can't upgrade to 2021031000

### ISSUE THREAD

**Issue by berthelemy** [moodlehq/filter_fulltranslate#6]
Moodle version: 3.10.2+
Current fulltranslate version: 2020042906

Having had an issue #4 with adding a Google API key, I want to upgrade to version 2021031000 of fulltranslate

When I try to do so, and go to upgrade the database, the site returns this error:

### filter_fulltranslate
Unknown error upgrading filter_fulltranslate to version 2021031000. Cannot continue.

### More information about this error

×Debug info:
Error code: upgradeerror
×Stack trace:
line 423 of /lib/upgradelib.php: upgrade_exception thrown
line 705 of /lib/upgradelib.php: call to upgrade_plugin_savepoint()
line 1922 of /lib/upgradelib.php: call to upgrade_plugins()
line 713 of /admin/index.php: call to upgrade_noncore()

Any ideas?

Thanks,

Mark

**Comment by berthelemy** [comment]
Just to add to this.

The error log shows the following:

[Thu Mar 25 16:04:18.855988 2021] [php7:notice] [pid 28438] [client 82.42.205.90:55406] Default exception handler: Unknown error upgrading filter_fulltranslate to version 2021031000. Cannot continue. Debug: \nError code: upgradeerror\n* line 423 of /lib/upgradelib.php: upgrade_exception thrown\n* line 705 of /lib/upgradelib.php: call to upgrade_plugin_savepoint()\n* line 1922 of /lib/upgradelib.php: call to upgrade_plugins()\n* line 713 of /admin/index.php: call to upgrade_noncore()\n, referer: https://academy.cabi.org/admin/index.php?cache=0&confirmrelease=1&confirmplugincheck=0&confirmupgrade=1

Not much help I'm afraid.

Mark

**Comment by berthelemy** [comment]
And one more thing to add:

We have tried a full reinstall of the plugin, using the most recent code. This also failed with the same unknown error.

Such a shame, as it looked so promising.

@andrewhancox Any thoughts?

**Comment by andrewhancox** [comment]
When you reinstalled it what did you do? If you uninstalled it and then reinstalled I would make sure that the filter_fulltranslate database table got remove successfully.

**Comment by berthelemy** [comment]
@andrewhancox Thanks for the advice. We removed the table manually and all is working well now.
